Anexia: extend disk configuration
anexia-it/machine-controller pull request #9
Opened 2022-08-11 11:49 UTC by LittleFox94

**What this PR does / why we need it**:

This extends the configuration for disks in provider Anexia. The important bit is the now-configurable disk performance type, but the config was revamped a bit to allow configuring multiple disks in the future.

**Special notes for your reviewer**:

In the first commit I did some cleanup of the config structs. This inflates the PR diff a bit, but it's separate commits at least.

The API changes are currently backwards compatible, so no "action required" needed for now.

**Optional Release Note**:

```release-note
Allow configuring the disk performance type for provider Anexia
```

2022-08-11 11:50 UTC, LittleFox94 commented
@marioreggiori could you take a first look at this, before I send this PR over to upstream? Many thanks :)

(refs ANXKUBE-650)

2022-08-11 13:06 UTC, marioreggiori requested changes
Code is looking good :+1:
We should update the example. I'm going to test the build now.

2022-08-11 13:06 UTC, marioreggiori commented on pkg/cloudprovider/provider/anexia/provider.go
> +		klog.Warningf("Configuration uses the deprecated DiskSize attribute, please migrate to the Disks array instead.")
I think we should update the example at `machine-controller/examples/anexia-machinedeployment.yaml` to use the new format.

2022-08-11 14:15 UTC, marioreggiori approved these changes

2022-10-12 10:33 UTC, LittleFox94 commented
merged upstream

2022-10-12 10:33 UTC, closed without merging